In [1]:
import pandas as pd
import requests
import os

# Topic 1: Linear Regression

The discussion will potentially cover the following questions:

* How to select explanatory variables?
* How to choose the right model and why? 
* How to interpret model results? How to interpret regression coefficients, such as margin, importance?

Specifically for predictive model, how to evaluate the predictive power of the model? e.g. in-sample v.s out-of-sample model errors, type I and type II errors, etc.

## Load Data

In [2]:
# Define get_example_ds function to download dataset to the current directory
def get_example_ds(stata_url,local_filename):
    try:
        # Download the file
        response = requests.get(stata_url, timeout=10)
        response.raise_for_status()  # Raise error for bad status codes

        # Save locally
        with open(local_filename, "wb") as f:
            f.write(response.content)
        print(f"Downloaded dataset to {os.path.abspath(local_filename)}")
    except requests.exceptions.RequestException as e:
        print(f"Error downloading dataset: {e}")
    except (ValueError, OSError) as e:
        print(f"Error reading dataset: {e}")

In [3]:
# Example: Download Stata's "auto.dta" dataset - Car
stata_url = "https://www.stata-press.com/data/r18/auto.dta"  # Change r18 to your Stata release if needed
local_filename = "auto.dta"

# Download dataset
get_example_ds(stata_url,local_filename)

# Load into pandas DataFrame
df_auto = pd.read_stata(local_filename)

# Preview the dataframe
df_auto.head()

Downloaded dataset to C:\Users\yuan.yuan\OneDrive - Summit, LLC\Documents\Python\auto.dta

,make,price,mpg,rep78,headroom,trunk,weight,length,turn,displacement,gear_ratio,foreign
0,AMC Concord,4099,22,3.0,2.5,11,2930,186,40,121,3.58,Domestic
1,AMC Pacer,4749,17,3.0,3.0,11,3350,173,40,258,2.53,Domestic
2,AMC Spirit,3799,22,NaN,3.0,12,2640,168,35,121,3.08,Domestic
3,Buick Century,4816,20,3.0,4.5,16,3250,196,40,196,2.93,Domestic
4,Buick Electra,7827,15,4.0,4.0,20,4080,222,43,350,2.41,Domestic

## Modeling - Linear Regression

In the first modeling exercise, we want to predict the gas efficiency of cars using car characteristics and potentially market variables.

In the car dataset, the `mpg` variable refers to miles per gallon. This dataset also provide other features such as the price, make, weight, mechanic and producer related informations.

### OLS Regression

In [4]:
import statsmodels.api as sm
import statsmodels.formula.api as smf
import numpy as np

In [5]:
df_auto=pd.read_stata(r'C:\Users\yuan.yuan\OneDrive - Summit, LLC\Documents\Python\auto.dta')

* make: The make and model of the car (string).
* price: The price of the car (integer).
* mpg: Mileage in miles per gallon (integer).
* rep78: Repair record for 1978 (integer).
* headroom: Headroom in inches (float).
* trunk: Trunk space in cubic feet (integer).
* weight: Weight of the car in pounds (integer).
* length: Length of the car in inches (integer).
* turn: Turn circle in feet (integer).
* displacement: Engine displacement in cubic inches (integer).
* gear_ratio: Gear ratio (float).
* foreign: Indicates whether the car is domestic or foreign (byte).

In [54]:
df_auto['make'].unique()

array(['AMC Concord', 'AMC Pacer', 'AMC Spirit', 'Buick Century',
       'Buick Electra', 'Buick LeSabre', 'Buick Opel', 'Buick Regal',
       'Buick Riviera', 'Buick Skylark', 'Cad. Deville', 'Cad. Eldorado',
       'Cad. Seville', 'Chev. Chevette', 'Chev. Impala', 'Chev. Malibu',
       'Chev. Monte Carlo', 'Chev. Monza', 'Chev. Nova', 'Dodge Colt',
       'Dodge Diplomat', 'Dodge Magnum', 'Dodge St. Regis', 'Ford Fiesta',
       'Ford Mustang', 'Linc. Continental', 'Linc. Mark V',
       'Linc. Versailles', 'Merc. Bobcat', 'Merc. Cougar',
       'Merc. Marquis', 'Merc. Monarch', 'Merc. XR-7', 'Merc. Zephyr',
       'Olds 98', 'Olds Cutl Supr', 'Olds Cutlass', 'Olds Delta 88',
       'Olds Omega', 'Olds Starfire', 'Olds Toronado', 'Plym. Arrow',
       'Plym. Champ', 'Plym. Horizon', 'Plym. Sapporo', 'Plym. Volare',
       'Pont. Catalina', 'Pont. Firebird', 'Pont. Grand Prix',
       'Pont. Le Mans', 'Pont. Phoenix', 'Pont. Sunbird', 'Audi 5000',
       'Audi Fox', 'BMW 320i', 'Datsun 200', 'Datsun 210', 'Datsun 510',
       'Datsun 810', 'Fiat Strada', 'Honda Accord', 'Honda Civic',
       'Mazda GLC', 'Peugeot 604', 'Renault Le Car', 'Subaru',
       'Toyota Celica', 'Toyota Corolla', 'Toyota Corona', 'VW Dasher',
       'VW Diesel', 'VW Rabbit', 'VW Scirocco', 'Volvo 260'], dtype=object)

In [53]:
# Can we use the dataset directly? 
col_y = 'mpg'
list_col_x = ['make', 'price', 'rep78', 'headroom', 'trunk', 'weight','length', 'turn', 'displacement', 'gear_ratio', 'foreign']
y = df_auto[col_y]
X = df_auto[list_col_x]

# Try the regular OLS method
model = sm.OLS(y, X).fit()
print(model.summary())

ValueError: Pandas data cast to numpy dtype of object. Check input data with np.asarray(data).

**Let's prepare the input dataset X properly**

In [55]:
# Examining the data
df_auto.head()
df_auto.describe()

,price,mpg,rep78,headroom,trunk,weight,length,turn,displacement,gear_ratio
count,74.000000,74.000000,69.000000,74.000000,74.000000,74.000000,74.000000,74.000000,74.000000,74.000000
mean,6165.256757,21.297297,3.405797,2.993243,13.756757,3019.459459,187.932432,39.648649,197.297297,3.014865
std,2949.495885,5.785503,0.989932,0.845995,4.277404,777.193567,22.266340,4.399354,91.837219,0.456287
min,3291.000000,12.000000,1.000000,1.500000,5.000000,1760.000000,142.000000,31.000000,79.000000,2.190000
25%,4220.250000,18.000000,3.000000,2.500000,10.250000,2250.000000,170.000000,36.000000,119.000000,2.730000
50%,5006.500000,20.000000,3.000000,3.000000,14.000000,3190.000000,192.500000,40.000000,196.000000,2.955000
75%,6332.250000,24.750000,4.000000,3.500000,16.750000,3600.000000,203.750000,43.000000,245.250000,3.352500
max,15906.000000,41.000000,5.000000,5.000000,23.000000,4840.000000,233.000000,51.000000,425.000000,3.890000

In [7]:
# Missing data imputation, e.g rep78, repair record in 1978, 1=poor - 5=excellent
df_data=df_auto.copy()
#df_data=df_data.dropna() # can simply drop missing data
df_data['rep_missing']=np.where(df_data['rep78'].isna(),1,0)
df_data.loc[df_data['rep78'].isna(),'rep78']=0
df_data.columns

Index(['make', 'price', 'mpg', 'rep78', 'headroom', 'trunk', 'weight',
       'length', 'turn', 'displacement', 'gear_ratio', 'foreign',
       'rep_missing'],
      dtype='object')

In [9]:
# Naive Way: Generate dummies for categorical variables
col_y = 'mpg'
y = df_data[col_y]

list_col_cat=['make','foreign','rep_missing']
list_col_cont=['rep78', 'headroom', 'trunk', 'weight',
       'length', 'turn', 'displacement', 'gear_ratio',]
X =pd.get_dummies(df_data[list_col_cat+list_col_cont], columns=list_col_cat, drop_first=True)
X = sm.add_constant(X)  # add intercept

# OLS
model = sm.OLS(y, X).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                    nan
Method:                 Least Squares   F-statistic:                       nan
Date:                Thu, 25 Jun 2026   Prob (F-statistic):                nan
Time:                        11:01:33   Log-Likelihood:                 1811.2
No. Observations:                  74   AIC:                            -3474.
Df Residuals:                       0   BIC:                            -3304.
Df Model:                          73
Covariance Type:            nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
const                      6.0047        inf          0        nan         nan         nan
rep78                      1.5980        inf          0        nan         nan         nan
headroom                   0.2772        inf          0        nan         nan         nan
trunk                     -0.1776        inf         -0        nan         nan         nan
weight                    -0.0093        inf         -0        nan         nan         nan
length                     0.0653        inf          0        nan         nan         nan
turn                       0.2367        inf          0        nan         nan         nan
displacement               0.0305        inf          0        nan         nan         nan
gear_ratio                 4.0338        inf          0        nan         nan         nan
make_AMC Pacer            -0.3259        inf         -0        nan         nan         nan
make_AMC Spirit            3.2637        inf          0        nan         nan         nan
make_Audi 5000            -4.9226        inf         -0        nan         nan         nan
make_Audi Fox             -3.1373        inf         -0        nan         nan         nan
make_BMW 320i              2.6288        inf          0        nan         nan         nan
make_Buick Century         0.9933        inf          0        nan         nan         nan
make_Buick Electra        -2.0378        inf         -0        nan         nan         nan
make_Buick LeSabre         1.5229        inf          0        nan         nan         nan
make_Buick Opel           -1.5398        inf         -0        nan         nan         nan
make_Buick Regal           1.2311        inf          0        nan         nan         nan
make_Buick Riviera         0.8169        inf          0        nan         nan         nan
make_Buick Skylark        -1.2736        inf         -0        nan         nan         nan
make_Cad. Deville         -1.0484        inf         -0        nan         nan         nan
make_Cad. Eldorado        -0.0274        inf         -0        nan         nan         nan
make_Cad. Seville          7.9359        inf          0        nan         nan         nan
make_Chev. Chevette        1.1971        inf          0        nan         nan         nan
make_Chev. Impala         -1.5691        inf         -0        nan         nan         nan
make_Chev. Malibu          5.8070        inf          0        nan         nan         nan
make_Chev. Monte Carlo     5.1919        inf          0        nan         nan         nan
make_Chev. Monza           4.3204        inf          0        nan         nan         nan
make_Chev. Nova            0.4825        inf          0        nan         nan         nan
make_Datsun 200           -3.4937        inf         -0        nan         nan         nan
make_Datsun 210            6.7072        inf          0        nan         nan         nan
make_Datsun 510           -1.6049        inf         -0        nan         nan         nan
make_Datsun 810           -2.9542        inf         -0        nan         nan         nan
make_Dodge Colt            0.4168        inf          0        nan         nan         nan
make_Dodge Diplomat        0.2255        inf          0        nan         nan         nan
make_Dodge Magnum         -1.7745        inf         -0        nan         nan         nan
make_Dodge St. Regis       1.1294        inf          0        nan         nan         nan
make_Fiat Strada          -1.7553        inf         -0        nan         nan         nan
make_Ford Fiesta           0.4427        inf          0        nan         nan         nan
make_Ford Mustang         -2.4618        inf         -0        nan         nan         nan
make_Honda Accord         -0.6196        inf         -0        nan         nan         nan
make_Honda Civic           0.2144        inf          0        nan         nan         nan
make_Linc. Continental    -0.2502        inf         -0        nan         nan         nan
make_Linc. Mark V         -0.8948        inf         -0        nan         nan         nan
make_Linc. Versailles     -1.4501        inf         -0        nan         nan         nan
make_Mazda GLC             3.3795        inf          0        nan         nan         nan
make_Merc. Bobcat         -1.1551        inf         -0        nan         nan         nan
make_Merc. Cougar         -4.8207        inf         -0        nan         nan         nan
make_Merc. Marquis        -0.6339        inf         -0        nan         nan         nan
make_Merc. Monarch         0.3503        inf          0        nan         nan         nan
make_Merc. XR-7           -3.0594        inf         -0        nan         nan         nan
make_Merc. Zephyr         -2.0026        inf         -0        nan         nan         nan
make_Olds 98               3.9065        inf          0        nan         nan         nan
make_Olds Cutl Supr       -0.4272        inf         -0        nan         nan         nan
make_Olds Cutlass         -1.2132        inf         -0        nan         nan         nan
make_Olds Delta 88         0.1701        inf          0        nan         nan         nan
make_Olds Omega           -1.8891        inf         -0        nan         nan         nan
make_Olds Starfire         6.1998        inf          0        nan         nan         nan
make_Olds Toronado         0.7445        inf          0        nan         nan         nan
make_Peugeot 604          -0.9428        inf         -0        nan         nan         nan
make_Plym. Arrow          12.0345        inf          0        nan         nan         nan
make_Plym. Champ           4.4158        inf          0        nan         nan         nan
make_Plym. Horizon         0.5068        inf          0        nan         nan         nan
make_Plym. Sapporo         2.4337        inf          0        nan         nan         nan
make_Plym. Volare         -2.1707        inf         -0        nan         nan         nan
make_Pont. Catalina        0.5242        inf          0        nan         nan         nan
make_Pont. Firebird        1.1931        inf          0        nan         nan         nan
make_Pont. Grand Prix     -2.2640        inf         -0        nan         nan         nan
make_Pont. Le Mans        -1.2813        inf         -0        nan         nan         nan
make_Pont. Phoenix         0.0296        inf          0        nan         nan         nan
make_Pont. Sunbird         3.5251        inf          0        nan         nan         nan
make_Renault Le Car        0.3424        inf          0        nan         nan         nan
make_Subaru                5.6893        inf          0        nan         nan         nan
make_Toyota Celica        -6.1828        inf         -0        nan         nan         nan
make_Toyota Corolla        5.1836        inf          0        nan         nan         nan
make_Toyota Corona        -4.1817        inf         -0        nan         nan         nan
make_VW Dasher            -3.7507        inf         -0        nan         nan         nan
make_VW Diesel            13.3268        inf          0        nan         nan         nan
make_VW Rabbit            -2.0687        inf         -0        nan         nan         nan
make_VW Scirocco          -1.6015        inf         -0        nan         nan         nan
make_Volvo 260            -2.1467        inf         -0        nan         nan         nan
foreign_Foreign           -1.8904        inf         -0        nan         nan         nan
rep_missing_1              3.2445        inf          0        nan         nan         nan
==============================================================================
Omnibus:                        6.403   Durbin-Watson:                   1.343
Prob(Omnibus):                  0.041   Jarque-Bera (JB):                5.620
Skew:                           0.603   Prob(JB):                       0.0602
Kurtosis:                       3.605   Cond. No.                     8.19e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.
[3] The condition number is large, 8.19e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

C:\Users\yuan.yuan\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1794: RuntimeWarning: divide by zero encountered in true_divide
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)
C:\Users\yuan.yuan\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1794: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)
C:\Users\yuan.yuan\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:1716: RuntimeWarning: divide by zero encountered in double_scalars
  return np.dot(wresid, wresid) / self.df_resid

In [56]:
# Re-do the categorical

df_data['make_r']=df_data['make'].apply(lambda x: x.split(' ')[0])
print(df_data['make_r'].unique())

col_y = 'mpg'
y = df_data[col_y]

list_col_cat=['make_r','foreign']
list_col_cont=['rep78', 'headroom', 'trunk', 'weight',
       'length', 'turn', 'displacement', 'gear_ratio', 'rep_missing']
X =pd.get_dummies(df_data[list_col_cat+list_col_cont], columns=list_col_cat, drop_first=True)
X = sm.add_constant(X)  # add intercept

# Try the regular OLS method
model = sm.OLS(y, X).fit()
print(model.summary())

['AMC' 'Buick' 'Cad.' 'Chev.' 'Dodge' 'Ford' 'Linc.' 'Merc.' 'Olds'
 'Plym.' 'Pont.' 'Audi' 'BMW' 'Datsun' 'Fiat' 'Honda' 'Mazda' 'Peugeot'
 'Renault' 'Subaru' 'Toyota' 'VW' 'Volvo']
                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.819
Model:                            OLS   Adj. R-squared:                  0.686
Method:                 Least Squares   F-statistic:                     6.133
Date:                Thu, 25 Jun 2026   Prob (F-statistic):           5.97e-08
Time:                        12:22:04   Log-Likelihood:                -171.14
No. Observations:                  74   AIC:                             406.3
Df Residuals:                      42   BIC:                             480.0
Df Model:                          31
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const              44.3788     11.040      4.020      0.000      22.100      66.658
rep78               1.4648      0.608      2.408      0.021       0.237       2.693
headroom           -0.3400      0.693     -0.491      0.626      -1.738       1.058
trunk              -0.0814      0.226     -0.361      0.720      -0.537       0.374
weight             -0.0023      0.003     -0.858      0.396      -0.008       0.003
length             -0.0976      0.103     -0.948      0.349      -0.305       0.110
turn               -0.0393      0.254     -0.155      0.878      -0.552       0.474
displacement       -0.0078      0.013     -0.584      0.562      -0.035       0.019
gear_ratio          0.0228      2.580      0.009      0.993      -5.184       5.229
rep_missing         4.4484      2.788      1.595      0.118      -1.179      10.075
make_r_Audi        -2.6040      2.468     -1.055      0.297      -7.585       2.377
make_r_BMW          2.1929      3.236      0.678      0.502      -4.337       8.722
make_r_Buick        3.4903      2.716      1.285      0.206      -1.990       8.971
make_r_Cad.         5.0289      3.380      1.488      0.144      -1.793      11.851
make_r_Chev.        4.2018      2.944      1.427      0.161      -1.740      10.144
make_r_Datsun       0.9550      2.130      0.448      0.656      -3.343       5.253
make_r_Dodge        4.6076      2.971      1.551      0.128      -1.388      10.604
make_r_Fiat        -2.7887      3.454     -0.807      0.424      -9.759       4.181
make_r_Ford        -0.3725      3.344     -0.111      0.912      -7.122       6.377
make_r_Honda       -0.5158      2.712     -0.190      0.850      -5.990       4.958
make_r_Linc.        2.7540      3.302      0.834      0.409      -3.909       9.417
make_r_Mazda        3.3843      3.267      1.036      0.306      -3.208       9.977
make_r_Merc.        1.0526      2.852      0.369      0.714      -4.702       6.807
make_r_Olds         4.4030      2.746      1.604      0.116      -1.138       9.944
make_r_Peugeot     -3.2099      3.989     -0.805      0.426     -11.260       4.840
make_r_Plym.        4.6610      2.517      1.852      0.071      -0.419       9.741
make_r_Pont.        3.3218      2.767      1.201      0.237      -2.262       8.906
make_r_Renault     -0.9259      3.570     -0.259      0.797      -8.131       6.280
make_r_Subaru       7.9149      3.296      2.401      0.021       1.264      14.566
make_r_Toyota      -2.9655      2.259     -1.313      0.196      -7.525       1.594
make_r_VW           2.3086      2.211      1.044      0.302      -2.154       6.772
make_r_Volvo       -3.9162      3.536     -1.108      0.274     -11.052       3.219
foreign_Foreign    -0.1703      2.307     -0.074      0.941      -4.826       4.485
==============================================================================
Omnibus:                       38.946   Durbin-Watson:                   2.683
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              117.752
Skew:                           1.646   Prob(JB):                     2.69e-26
Kurtosis:                       8.230   Cond. No.                     1.03e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 6.79e-24. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [11]:
# Try fit a R style equation, customize the equation by yourself
equation = 'mpg ~ rep78:rep_missing + weight + displacement + C(foreign)'
model_r = smf.ols(equation, data=df_data).fit()
print(model_r.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.663
Model:                            OLS   Adj. R-squared:                  0.648
Method:                 Least Squares   F-statistic:                     45.88
Date:                Thu, 25 Jun 2026   Prob (F-statistic):           1.64e-16
Time:                        11:01:51   Log-Likelihood:                -194.16
No. Observations:                  74   AIC:                             396.3
Df Residuals:                      70   BIC:                             405.5
Df Model:                           3
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
Intercept                41.8479      2.351     17.802      0.000      37.160      46.536
C(foreign)[T.Foreign]    -1.6006      1.114     -1.437      0.155      -3.822       0.620
rep78:rep_missing      7.352e-13   4.25e-14     17.285      0.000     6.5e-13     8.2e-13
weight                   -0.0068      0.001     -5.807      0.000      -0.009      -0.004
displacement              0.0019      0.010      0.192      0.849      -0.018       0.022
==============================================================================
Omnibus:                       37.855   Durbin-Watson:                   2.431
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               92.155
Skew:                           1.728   Prob(JB):                     9.75e-21
Kurtosis:                       7.236   Cond. No.                     1.23e+19
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.8e-30. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

### How to evaluate the model fit? 

* Statistics

    * R² and Adj. R²: Measures the proportion of variance in the dependent variable explained by your model. (Closer to 1.0 is better).
    * Log-Likelihood: Measures the probability of observing the given data under your fitted model. Useful for comparing two models (higher values are better).
    * AIC & BIC: Penalized versions of log-likelihood that account for the number of predictors. These are useful for comparing multiple models (lower values are better).

* Hypothesis Testing

    * F-statistic: Tests the overall significance of the model. If the Prob(F-statistic) is lower than your significance level (e.g., 0.05), the model fits significantly better than a flat line with no predictors.
    * p-values: Located in the coefficient table, these evaluate if individual predictors meaningfully contribute to the model.
    
* Evaluate Underline Assumptions

    * Residual Normality: Check the Omnibus test or Jarque-Bera (JB) test in the summary (low p-values indicate residuals are not normally distributed).
    * Autocorrelation: Use the Durbin-Watson statistic. A value near 2.0 suggests no autocorrelation in the residuals.
    * Multicollinearity: Check the Condition Number. Values above 20 to 30 often indicate severe multicollinearity.

In [12]:
print(model.summary())
print('AIC: ', model.aic)
print('BIC: ', model.bic)

                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.819
Model:                            OLS   Adj. R-squared:                  0.686
Method:                 Least Squares   F-statistic:                     6.133
Date:                Thu, 25 Jun 2026   Prob (F-statistic):           5.97e-08
Time:                        11:01:59   Log-Likelihood:                -171.14
No. Observations:                  74   AIC:                             406.3
Df Residuals:                      42   BIC:                             480.0
Df Model:                          31
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const              44.3788     11.040      4.020      0.000      22.100      66.658
rep78               1.4648      0.608      2.408      0.021       0.237       2.693
headroom           -0.3400      0.693     -0.491      0.626      -1.738       1.058
trunk              -0.0814      0.226     -0.361      0.720      -0.537       0.374
weight             -0.0023      0.003     -0.858      0.396      -0.008       0.003
length             -0.0976      0.103     -0.948      0.349      -0.305       0.110
turn               -0.0393      0.254     -0.155      0.878      -0.552       0.474
displacement       -0.0078      0.013     -0.584      0.562      -0.035       0.019
gear_ratio          0.0228      2.580      0.009      0.993      -5.184       5.229
rep_missing         4.4484      2.788      1.595      0.118      -1.179      10.075
make_r_Audi        -2.6040      2.468     -1.055      0.297      -7.585       2.377
make_r_BMW          2.1929      3.236      0.678      0.502      -4.337       8.722
make_r_Buick        3.4903      2.716      1.285      0.206      -1.990       8.971
make_r_Cad.         5.0289      3.380      1.488      0.144      -1.793      11.851
make_r_Chev.        4.2018      2.944      1.427      0.161      -1.740      10.144
make_r_Datsun       0.9550      2.130      0.448      0.656      -3.343       5.253
make_r_Dodge        4.6076      2.971      1.551      0.128      -1.388      10.604
make_r_Fiat        -2.7887      3.454     -0.807      0.424      -9.759       4.181
make_r_Ford        -0.3725      3.344     -0.111      0.912      -7.122       6.377
make_r_Honda       -0.5158      2.712     -0.190      0.850      -5.990       4.958
make_r_Linc.        2.7540      3.302      0.834      0.409      -3.909       9.417
make_r_Mazda        3.3843      3.267      1.036      0.306      -3.208       9.977
make_r_Merc.        1.0526      2.852      0.369      0.714      -4.702       6.807
make_r_Olds         4.4030      2.746      1.604      0.116      -1.138       9.944
make_r_Peugeot     -3.2099      3.989     -0.805      0.426     -11.260       4.840
make_r_Plym.        4.6610      2.517      1.852      0.071      -0.419       9.741
make_r_Pont.        3.3218      2.767      1.201      0.237      -2.262       8.906
make_r_Renault     -0.9259      3.570     -0.259      0.797      -8.131       6.280
make_r_Subaru       7.9149      3.296      2.401      0.021       1.264      14.566
make_r_Toyota      -2.9655      2.259     -1.313      0.196      -7.525       1.594
make_r_VW           2.3086      2.211      1.044      0.302      -2.154       6.772
make_r_Volvo       -3.9162      3.536     -1.108      0.274     -11.052       3.219
foreign_Foreign    -0.1703      2.307     -0.074      0.941      -4.826       4.485
==============================================================================
Omnibus:                       38.946   Durbin-Watson:                   2.683
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              117.752
Skew:                           1.646   Prob(JB):                     2.69e-26
Kurtosis:                       8.230   Cond. No.                     1.03e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 6.79e-24. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
AIC:  406.27516189803805
BIC:  480.00524488057147

In [13]:
# Evaluate Model Performance, in-sample

from statsmodels.tools.eval_measures import mse

# Generate predictions from your fitted model
predictions = model.predict(X)

# Calculate the Mean Squared Error
error = mse(y, predictions)
print(f"Mean Squared Error: {error}")

Mean Squared Error: 5.974276240836366

### Logistic Regression

* Convert the `mpg` variable to a categorical variable as follows and fit a logistic regression model. 
* How should we interprete the model result?
* How to evaluate the model performance?

In [65]:
# Generate categorical variable mpg_bins
labels=['low','high']
cutoff=25
bins=[1,cutoff,df_auto['mpg'].max()+1]
df_data['mpg_bins'] = pd.cut(x=df_data['mpg'], bins=bins,labels=labels)
df_data.head()
df_data.pivot_table(index='mpg_bins',aggfunc='count')

,displacement,foreign,gear_ratio,headroom,length,make,make_r,mpg,price,rep78,rep_missing,trunk,turn,weight
mpg_bins,,,,,,,,,,,,,,
low,60,60,60,60,60,60,60,60,60,60,60,60,60,60
high,14,14,14,14,14,14,14,14,14,14,14,14,14,14

In [66]:
df_data['mpg_bins']=np.where(df_data['mpg']>=cutoff, 1, 0)

In [67]:
# Customize the equation and fit the logistic regression model
equation = 'mpg_bins ~ length + weight + displacement + C(foreign)'
model = smf.logit(formula=equation, data=df_data)
results = model.fit()
print(results.summary())

Optimization terminated successfully.
         Current function value: 0.209042
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:               mpg_bins   No. Observations:                   74
Model:                          Logit   Df Residuals:                       69
Method:                           MLE   Df Model:                            4
Date:                Thu, 25 Jun 2026   Pseudo R-squ.:                  0.6330
Time:                        12:47:29   Log-Likelihood:                -15.469
converged:                       True   LL-Null:                       -42.153
Covariance Type:            nonrobust   LLR p-value:                 7.137e-11
=========================================================================================
                            coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------
Intercept                32.4035     11.069      2.927      0.003      10.708      54.099
C(foreign)[T.Foreign]    -1.0849      1.229     -0.883      0.377      -3.493       1.323
length                   -0.1625      0.075     -2.170      0.030      -0.309      -0.016
weight                   -0.0018      0.002     -0.972      0.331      -0.005       0.002
displacement              0.0008      0.011      0.069      0.945      -0.021       0.022
=========================================================================================

Possibly complete quasi-separation: A fraction 0.14 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.

**Confusion Matrix**

* matrix[0, 0]: True Negatives (TN)
* matrix[0, 1]: False Positives (FP)
* matrix[1, 0]: False Negatives (FN)
* matrix[1, 1]: True Positives (TP)

In [70]:
confusion_matrix = results.pred_table(threshold=0.3)
print(confusion_matrix)

[[48.  7.]
 [ 3. 16.]]

In [71]:
# Plot ROC AUC

## Rank the variable importance

In [20]:
df_data.corr()

,price,mpg,rep78,headroom,trunk,weight,length,turn,displacement,gear_ratio,rep_missing,mpg_bins
price,1.000000,-0.468597,-0.011667,0.114506,0.314332,0.538611,0.431831,0.309617,0.494943,-0.313661,0.024364,-0.253145
mpg,-0.468597,1.000000,0.289326,-0.413803,-0.581585,-0.807175,-0.795779,-0.719186,-0.705643,0.616177,0.004811,0.793249
rep78,-0.011667,0.289326,1.000000,-0.087037,-0.014539,-0.252377,-0.223958,-0.274666,-0.280459,0.212842,-0.669314,0.258238
headroom,0.114506,-0.413803,-0.087037,1.000000,0.662011,0.483456,0.516295,0.424465,0.474491,-0.377852,-0.029872,-0.289796
trunk,0.314332,-0.581585,-0.014539,0.662011,1.000000,0.672206,0.726596,0.601059,0.608635,-0.508665,-0.149331,-0.410515
weight,0.538611,-0.807175,-0.252377,0.483456,0.672206,1.000000,0.946009,0.857443,0.894896,-0.759258,-0.060490,-0.666827
length,0.431831,-0.795779,-0.223958,0.516295,0.726596,0.946009,1.000000,0.864261,0.835140,-0.696383,-0.060038,-0.698990
turn,0.309617,-0.719186,-0.274666,0.424465,0.601059,0.857443,0.864261,1.000000,0.776765,-0.676300,-0.126210,-0.632379
displacement,0.494943,-0.705643,-0.280459,0.474491,0.608635,0.894896,0.835140,0.776765,1.000000,-0.828877,-0.028619,-0.512998
gear_ratio,-0.313661,0.616177,0.212842,-0.377852,-0.508665,-0.759258,-0.696383,-0.676300,-0.828877,1.000000,0.127787,0.521331
rep_missing,0.024364,0.004811,-0.669314,-0.029872,-0.149331,-0.060490,-0.060038,-0.126210,-0.028619,0.127787,1.000000,0.088269
mpg_bins,-0.253145,0.793249,0.258238,-0.289796,-0.410515,-0.666827,-0.698990,-0.632379,-0.512998,0.521331,0.088269,1.000000

In [21]:
df_data.columns

Index(['make', 'price', 'mpg', 'rep78', 'headroom', 'trunk', 'weight',
       'length', 'turn', 'displacement', 'gear_ratio', 'foreign',
       'rep_missing', 'make_r', 'mpg_bins'],
      dtype='object')

In [75]:
def gen_results(equation,df_data,df_sum):
    model=smf.ols(equation, data=df_data).fit()
    r2=model.rsquared
    r2_adj=model.rsquared_adj
    aic=model.aic
    return pd.concat([df_sum,pd.DataFrame({'equation':[equation],'r2':[r2],'r2_adj':[r2_adj],'aic':[aic]})],axis=0)

In [76]:
df_sum=pd.DataFrame(columns=['equation','r2','r2_adj','aic'])

eq = 'mpg ~ weight'
df_sum=gen_results(eq,df_data,df_sum)

eq = 'mpg ~ weight + length'
df_sum=gen_results(eq,df_data,df_sum)

eq = 'mpg ~ weight + length + C(make_r)'
df_sum=gen_results(eq,df_data,df_sum)

In [77]:
df_sum

                            equation        r2    r2_adj         aic
0                       mpg ~ weight  0.651531  0.646691  394.777377
0              mpg ~ weight + length  0.661390  0.651852  394.653524
0  mpg ~ weight + length + C(make_r)  0.787553  0.683497  404.158015

In [78]:
#eq = 'mpg ~ rep78:rep_missing + weight + displacement + C(foreign)'
df_data.columns

Index(['make', 'price', 'mpg', 'rep78', 'headroom', 'trunk', 'weight',
       'length', 'turn', 'displacement', 'gear_ratio', 'foreign',
       'rep_missing', 'make_r', 'mpg_bins'],
      dtype='object')